---
apiVersion: v1
kind: Pod
metadata: 
   name: httpd-rc
   namespace: test-ns
   labels: 
      type: proxy
      author: ravindra
spec: 
  containers: 
    - name: myhttpd
      image: httpd
      ports: 
       - containerPort: 80
         hostPort: 6060
...
