---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        type: nginx-app
    spec:
      containers:
        - name: mynginx
          image: nginx
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-volume
          emptyDir: {}
...
