---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      type: php-apache-app
  template:
    metadata:
      name: php-apache-pod
      labels:
        type: php-apache-app
    spec:
      containers:
        - name: php-apache
          image: intelliqit/mynew
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 150m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
  labels:
    type: php-apache-app
spec:
  selector:
    type: php-apache
  ports: 
     - port: 80
...
