---
apiVersion: v1
kind: ReplicationController
metadata: 
   name: httpd-rc
   labels: 
      type: proxy
      author: ravindra
spec: 
   replicas: 2
   template: 
     metadata: 
       name: httpd-pod
       labels: 
          type: proxy
     spec: 
       containers: 
         - name: myhttpd
           image: httpd
           ports: 
              - containerPort: 80
                hostPort: 6060
...
