---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: httpd-deployment
   labels: 
      type: webserver
      author: ravindra
spec: 
   replicas: 2
   selector: 
      matchLabels: 
         type: webserver
   template: 
      metadata: 
         name: httpd-pod
         labels: 
            type: webserver
      spec: 
         containers: 
            - name: webserver
              image: httpd
...
