---
apiVersion: v1
kind: Secret
metadata: 
   name: mysql-secret
   labels: 
      type: mydb-app
type: Opeque
stringData: 
   a: bXZicm90aGVycwo=

---
apiVersion: v1
kind: Pod
metadata: 
   name: mysql-pod
   labels: 
      type: mydb-app
spec: 
   containers: 
      - name: mydb 
        image: mysql:5
        env: 
           - name: MYSQL_ROOT_PASSWORD
             valueFrom: 
                secretKeyRef: 
                   name: mysql-secret
                   key: a
...
