---
apiVersion: v1
kind: Service
metadata: 
   name: nginx-service
   labels: 
      author: ravindra
spec: 
   type: NodePort
   ports: 
      - targetPort: 80
        port: 80
        nodePort: 30009
   selector: 
         type: proxy
         author: ravindra
...
