---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: tomcat-app
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: tomcat-app
    spec:
      containers:
        - name: mytomcat
          image: tomee
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: slave1
                    operator: In
                    values:
                      - intelliqit1
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    type: tomcat-app
spec:
  selector:
    type: tomcat-app
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
...
