---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: httpd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: httpd-app
  template:
    metadata:
      name: httpd-pod
      labels:
        type: httpd-app
    spec:
      containers:
        - name: myhttpd
          image: httpd
      nodeSelector:
        slave: intelliqit
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    type: httpd-app
spec:
  type: NodePort
  selector:
    type: httpd-app
  ports:
    - targetPort: 80
      port: 80
...
