---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: nginx-app
spec:
  containers:
    - name: mynginx
      image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: slave1
                operator: In
                values:
                  - intelliqit1
          topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: nginx-app
spec:
  selector:
    type: nginx-app
  ports:
    - targetPort: 80
      port: 80
  type: LoadBalancer
...
