---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: httpd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: httpd-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: httpd-pod
      labels:
        type: httpd-app
    spec:
      containers:
        - name: myhttpd
          image: httpd
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                 - key: slave1
                   operator: In
                   values:
                    - intelliqit
              topologyKey: kubernetes.io/ap-southeast-1
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    type: httpd-app
spec:
  type: LoadBalancer
  selector:
    type: httpd-app
  ports:
    - targetPort: 80
      port: 80
...
