---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        type: nginx-app
    spec:
      containers:
        - name: mynginx
          image: nginx
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                 matchExpressions:
                   - key: slave
                     operator: In
                     values:
                       - intelliqit
              topologyKey: kubernetes.io/ap-southeast-1

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: nginx-app
spec:
  type: LoadBalancer
  selector:
    type: nginx-app
  ports:
    - targetPort: 80
      port: 80
...