---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opeque
stringData:
  password: mvbrothers
  username: myuser
  dbname: mydb
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
  labels: 
    type: postgres-app
spec: 
  selector: 
    matchLabels: 
      type: postgres-app
  template: 
    metadata: 
      name: postgres-pod
      labels: 
        type: postgres-app
    spec:
       containers:
          - name: mydb
            image: postgres
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                   secretKeyRef:
                       name: postgres-secret
                       key: password
              - name: POSTGRES_USER
                valueFrom:
                   secretKeyRef:
                      name: postgres-secret
                      key: username
              - name: POSTGRES_DB
                valueFrom:
                   secretKeyRef:
                      name: postgres-secret
                      key: dbname
... 
