---
apiVersion: v1
kind: Pod
metadata: 
   name: postgres
   labels: 
      type: proxy
      author: ravindra
spec: 
   containers: 
     - name: mydb
       image: postgres
       env: 
         - name: POSTGRES_PASSWORD
           value: mvbrothers
         - name: POSTGRES_USER
           value: myuser
         - name: POSTGRES_DB
           value: mydb
...


