---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    type: pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: httpd-app
spec:
  containers:
    - name: myhttpd
      image: httpd
      volumeMounts:
        - name: my-volume
          mountPath: /usr/local/apache2/htdocs/
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
...

...
