---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: httpd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: httpd-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: httpd-pod
      labels:
        type: httpd-app
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 6060
...
