---
apiVersion: v1
kind: Pod
metadata: 
   name: tomcat-pod
   labels: 
      type: tomcat-app
spec: 
   containers: 
      - name: mytomcat
        image: tomcat
        resources: 
           requests: 
              memory: "64Mi"
              cpu: "250m"
           limits: 
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata: 
   name: tomcat-service
   labels: 
      type: tomcat-app
spec: 
   type: LoadBalancer
   selector: 
      type: tomcat-app
   ports: 
      - targetPort: 8080
        port: 8080
...
