---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    type: mysql-app
type: Opaque
stringData:
  a: intelliqit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: mysql-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: mysql-app
  template:
    metadata:
      name: mysql-pod
      labels:
        type: mysql-app
    spec:
      containers:
        - name: mydb
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: a
...
