---
apiVersion: v1
kind: Service
metadata: 
   name: httpd-service
   labels: 
      author: ravindra
spec: 
   type: LoadBalancer
   ports: 
      - targetPort: 80
        port: 80
        nodePort: 30008
   selector: 
      type: webserver
      author: ravindra
...
