---
apiVersion: v1
kind: Service
metadata: 
   name: nginx-service
   labels: 
      type: proxy
spec: 
   type: LoadBalancer
   selector: 
      type: proxy 
   ports: 
      - targetPort: 80
        port: 80
