---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: httpd-app
spec:
  containers:
    - name: myhttpd
      image: httpd
  tolerations:
    - key: slave2
      operator: Equal
      value: intelliait2
      effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    type: httpd-app
spec:
  type: NodePort
  selector:
    type: httpd-app
  ports:
    - targetPort: 80
      port: 80
...
