---
apiVersion: v1
kind: Pod
metadata: 
   name: tomcat-pod
   labels: 
      type: proxy
      author: ravindra
spec: 
   containers: 
      - name: appserver
        image: tomee
        ports: 
           - containerPort: 8080
             hostPort: 7070
...

